<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="deck_1\C10.png" />
    <None Remove="deck_1\C2.png" />
    <None Remove="deck_1\C3.png" />
    <None Remove="deck_1\C4.png" />
    <None Remove="deck_1\C5.png" />
    <None Remove="deck_1\C6.png" />
    <None Remove="deck_1\C7.png" />
    <None Remove="deck_1\C8.png" />
    <None Remove="deck_1\C9.png" />
    <None Remove="deck_1\CA.png" />
    <None Remove="deck_1\CJ.png" />
    <None Remove="deck_1\CK.png" />
    <None Remove="deck_1\CQ.png" />
    <None Remove="deck_1\D10.png" />
    <None Remove="deck_1\D2.png" />
    <None Remove="deck_1\D3.png" />
    <None Remove="deck_1\D4.png" />
    <None Remove="deck_1\D5.png" />
    <None Remove="deck_1\D6.png" />
    <None Remove="deck_1\D7.png" />
    <None Remove="deck_1\D8.png" />
    <None Remove="deck_1\D9.png" />
    <None Remove="deck_1\DA.png" />
    <None Remove="deck_1\DJ.png" />
    <None Remove="deck_1\DK.png" />
    <None Remove="deck_1\DQ.png" />
    <None Remove="deck_1\H10.png" />
    <None Remove="deck_1\H2.png" />
    <None Remove="deck_1\H3.png" />
    <None Remove="deck_1\H4.png" />
    <None Remove="deck_1\H5.png" />
    <None Remove="deck_1\H6.png" />
    <None Remove="deck_1\H7.png" />
    <None Remove="deck_1\H8.png" />
    <None Remove="deck_1\H9.png" />
    <None Remove="deck_1\HA.png" />
    <None Remove="deck_1\HJ.png" />
    <None Remove="deck_1\HK.png" />
    <None Remove="deck_1\HQ.png" />
    <None Remove="deck_1\S10.png" />
    <None Remove="deck_1\S2.png" />
    <None Remove="deck_1\S3.png" />
    <None Remove="deck_1\S4.png" />
    <None Remove="deck_1\S5.png" />
    <None Remove="deck_1\S6.png" />
    <None Remove="deck_1\S7.png" />
    <None Remove="deck_1\S8.png" />
    <None Remove="deck_1\S9.png" />
    <None Remove="deck_1\SA.png" />
    <None Remove="deck_1\SJ.png" />
    <None Remove="deck_1\SK.png" />
    <None Remove="deck_1\SQ.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="deck_1\C10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\C2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\C3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\C4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\C5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\C6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\C7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\C8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\C9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\CA.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\CJ.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\CK.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\CQ.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\D10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\D2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\D3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\D4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\D5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\D6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\D7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\D8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\D9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\DA.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\DJ.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\DK.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\DQ.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\H10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\H2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\H3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\H4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\H5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\H6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\H7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\H8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\H9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\HA.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\HJ.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\HK.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\HQ.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\S10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\S2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\S3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\S4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\S5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\S6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\S7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\S8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\S9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\SA.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\SJ.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\SK.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="deck_1\SQ.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>